#include "matrix.h"
using namespace std;
#define MAX 1000
// do not edit this file

int main(int argc, char **argv) {
    int n;
    cin >> n;
    Matrix* A = new Matrix(n,n);
    Matrix* B = new Matrix(n,n);
    // tests the matrix multiplication of random n by n matrix
    for (int i=0; i<n; i++) {
        for (int j=0; j<n; j++) {
            A->set(i,j,rand()%MAX);
            B->set(i,j,rand()%MAX);
        }
    }
    auto start = chrono::high_resolution_clock::now();
    Matrix* C = A->multiplyMatrix(B);
    auto end = chrono::high_resolution_clock::now();
    auto elapsed = chrono::duration_cast<chrono::duration<double>>(end - start);
    cout <<elapsed.count()<<"\n";
    A->~Matrix();
    B->~Matrix();
    C->~Matrix();
    return 0;
}